parser: babel-eslint

env:
  es6: true
  browser: true
  node: true

plugins:
- react
- ramda

extends:
- airbnb
- plugin:ramda/recommended

settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules
      - src/
rules:
  # react/jsx-sort-props: 0
  consistent-return: 0
  function-paren-newline: 0
  implicit-arrow-linebreak: 0
  import/prefer-default-export: 0
  jsx: never
  lines-between-class-members: 0
  no-shadow: 0
  no-underscore-dangle: 0
  no-unused-expressions: 0
  no-use-before-define: 0
  no-mixed-operators: 0
  no-nested-ternary: 0
  no-multi-spaces: 0
  key-spacing: 0
  object-curly-newline: 0
  prefer-destructuring: 0
  react/destructuring-assignment: 0
  react/no-multi-comp: 0
  react/no-unused-prop-types: 0
  react/prop-types: 0
  react/require-default-props: 0

  comma-spacing: 0

  comma-dangle:
  - error
  - arrays: always-multiline
    objects: always-multiline
    imports: always-multiline
    exports: always-multiline
    functions: always-multiline

  import/extensions:
  - error
  - always
  - js: never
  - jsx: never
  no-multiple-empty-lines:
  - error
  - max: 2

  no-console:
  - warn
  - allow:
    - warn
    - error
    - groupEnd

  space-before-function-paren:
  - error
  - always

  react/sort-comp:
  - 2
  - order:
    - type-annotations
    - instance-variables
    - static-methods
    - lifecycle
    - render
    - everything-else

  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - rollup.config.js
