backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/pages/main/index.md"
        label: "Main Page"
        name: "main"
        fields:
          - {label: Path, name: path, widget: hidden, default: '/'}
          - {label: Intro, name: intro, widget: text}
          - label: Menus
            name: menus
            widget: list
            fields:
              - label: Dishes
                name: dishes
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Price
                    name: price
                    required: false
                    widget: string
                  - label: Alternatives
                    name: alternatives
                    default: []
                    widget: list
                    fields:
                      - label: Name
                        name: name
                        widget: string
                      - label: Price
                        widget: string
                        required: false
                        name: price
          - label: Catering Menus
            name: menusCatering
            widget: list
            fields:
              - label: Dishes
                name: dishes
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Price
                    name: price
                    required: false
                    widget: string
                  - label: Alternatives
                    name: alternatives
                    default: []
                    widget: list
                    fields:
                      - label: Name
                        name: name
                        widget: string
                      - label: Price
                        widget: string
                        required: false
                        name: price
          - {label: Info, name: info, widget: text}
