backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/pages/main/index.md"
        label: "Main Page"
        name: "main"
        fields:
          - {label: Intro, name: intro, widget: string}
          - label: Menus
            name: menus
            widget: list
            fields:
              - label: Dishes
                name: dishes
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Price
                    name: price
                    widget: number
                  - label: Alternatives
                    name: alternatives,
                    widget: list
                    fields:
                      - label: Name
                        name: name
                        widget: string
                      - label: Price
                        widget: number
                        name: price
          - label: Catering Menus
            name: menusCatering
            widget: list
            fields:
              - label: Dishes
                name: dishes
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Price
                    name: price
                    widget: number
                  - label: Alternatives
                    name: alternatives,
                    widget: list
                    fields:
                      - label: Name
                        name: name
                        widget: string
                      - label: Price
                        widget: number
                        name: price
          - {label: Number, name: number, widget: string}
          - {label: Address, name: address, widget: string}
